name: Docker Image CI

on:
  push:
    branches:
      - "master"
      - "releases/**"
  pull_request:
    branches:
      - "master"
      - "releases/**"
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push the Image
      uses: docker/build-push-action@v6
      env:
        DOCKER_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_TAG: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref_name }}
      with:
        context: ./1.20.0
        platforms: linux/amd64
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ env.DOCKER_NAMESPACE }}/unbound-docker:${{ env.IMAGE_TAG }}
